authorName: fusionby2030
experimentName: simple-VAE-search
trialConcurrency: 1
maxExecDuration: 18h
maxTrialNum: 5000
trainingServicePlatform: local
searchSpacePath: search-space.json
useAnnotation: false
tuner:
  builtinTunerName: MetisTuner
  classArgs:
    optimize_mode: maximize
trial:
        command: python3 simple_VAE_search.py
        codeDir: ..
        gpuNum: 0
